config/routes.rb
Rails.application.routes.draw do

  # resources :news, except: [:index]

  root 'home#index'
  get '/faq' => 'faq#index'
  # get '/index' => 'home#index'
  get '/contact' => 'contact#contact'
  get '/facts' => 'facts#index'
  get '/airport' => 'airport#index'
  get '/jobs' => 'jobs#index'
  get '/deal' => 'deal#index'
  get '/news' => 'news#display'

  get '/guarantee' => 'pdf#index'

  # get '/admin/news' => 'news#index'
  # get '/admin/news/new' => 'news#new'
  # post '/admin/news' => 'news#create'
  # get '/admin/news/:id/' => 'news#show'
  # get '/admin/news/:id/edit' => 'news#edit'
  # put '/admin/news/:id' => 'news#update'
  # delete '/admin/news/:id' => 'news#destroy'


  end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :outlet

  before_validation do
    self.content = content.truncate(299, :omission => '...')  
  end
end

app/models/outlet.rb
class Outlet < ActiveRecord::Base
  has_many :articles
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/airport_controller.rb
class AirportController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
# class ContactController < ApplicationController
#
#   def contact
#   end
#
# end

app/controllers/deal_controller.rb
class DealController < ApplicationController

end

app/controllers/facts_controller.rb
class FactsController < ApplicationController


end

app/controllers/faq_controller.rb
class FaqController < ApplicationController

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @articles = Article.order(date_published: :desc).limit(4)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController


end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_article, only: [:edit, :update, :destroy]

  def display
    @articles = Article.order(date_published: :desc)
  end

  def index
    @articles = Article.order(date_published: :desc)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to admin_news_path, notice: 'Article was successfully created.'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to admin_news_path, notice: 'Article was successfully updated.'
    end
  end

  def destroy
    @article.destroy
      redirect_to admin_news_path, notice: 'Article was successfully destroyed.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:headline, :author, :content, :url, :outlet_id, :date_published)
  end


end

app/controllers/pdf_controller.rb
class PdfController < ApplicationController

  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/airport/airport.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Bermuda Badly Needs a New Airport Terminal</h1>

        </div>
    </div>

    <iframe width="560" height="315" src="https://www.youtube.com/embed/4smMBCsaong" frameborder="0" allowfullscreen></iframe>


    <hr>

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12">
            <p>A study commissioned by the former government determined that the current airport terminal’s useful life ended in 2008. The building is well past its expiration date, and operating on borrowed time.</p>

            <p>Parts of the facility were built in the 1940s – nearly 70 years ago. The rest was added piecemeal – with additions built in the 1950s, 1960s, and 1980s. The result is a shabby, haphazard facility that is difficult to operate and expensive to maintain.</p>

            <p>Since the airport was built in phases, the parts built long ago are settling at a different rate then the newer ones. That means the facility is now twisting itself apart because it was not built on solid ground.</p>

            <p>When it rains outside it rains inside. The sewage system is below sea level so when the tide is high and the wind is in the east, the toilets at our airport do not flush. The carpeting and flooring has had to be replaced several times because the sewage comes up from underneath.</p>

            <p>Most alarming of all, the current terminal is in the worst possible location when it comes to exposure to severe weather. Hurricane winds often come out of the northeast into Castle Harbour. As a result, the sea builds itself up at precisely the area where the current airport stands, flooding it and its surroundings.</p>

            <p>After Hurricane Fahy, which was not a particularly strong hurricane, the airport suffered extensive damage. After Hurricane Fabian, the roof nearly collapsed, which would have completely destroyed the terminal. Next time we may not be so lucky.</p>

            <p>As long as the terminal is in its current location, it will always be susceptible to storm damage because it’s located too close to the water. That’s why the airport redevelopment project would move the terminal 300 meters away from Castle Harbour and raise it 5 meters above sea level to help protect the building from storm damage. Bermuda’s economy and people suffer when our airport has to be shut down, which is going to happen more and more often as long as we continue to neglect this problem.</p>
            <br>
            <h4>Why not just repair the current airport?</h4>
            <br>
            <p>There are some who argue that we should simply fix the current terminal rather than build a new one. Yet repairing the terminal would cost at least $115 million – and Bermuda would still be left with an old airport. The maintenance problems might go away temporarily, but it would still be the old airport with all its faults and inconveniences.<p>

            <p>The repaired facility would not have the features you find in modern airports, like jet bridges, and it would not be wheelchair-friendly. Above all, the airport would still be located too close to the water.</p>
        </div>
    </div>
    <!-- /.row -->

    <hr>



    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <!-- <p>Copyright &copy; Your Website 2014</p> -->
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

app/views/airport/index.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-7">
            <h1 class="page-header">Bermuda Badly Needs a New Airport Terminal</h1>

        </div>
    </div>

    <iframe width="560" height="315" src="https://www.youtube.com/embed/hl19kMIdeHU" frameborder="0" allowfullscreen></iframe>


    <hr>

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-7">
            <p>A study commissioned by the former government determined that the current airport terminal’s useful life ended in 2008. The building is well past its expiration date, and operating on borrowed time.</p>

            <p>Parts of the facility were built in the 1940s – nearly 70 years ago. The rest was added piecemeal – with additions built in the 1950s, 1960s, and 1980s. The result is a shabby, haphazard facility that is difficult to operate and expensive to maintain.</p>

            <p>Since the airport was built in phases, the parts built long ago are settling at a different rate then the newer ones. That means the facility is now twisting itself apart because it was not built on solid ground.</p>

            <p>When it rains outside it rains inside. The sewage system is below sea level so when the tide is high and the wind is in the east, the toilets at our airport do not flush. The carpeting and flooring has had to be replaced several times because the sewage comes up from underneath.</p>

            <p>Most alarming of all, the current terminal is in the worst possible location when it comes to exposure to severe weather. Hurricane winds often come out of the northeast into Castle Harbour. As a result, the sea builds itself up at precisely the area where the current airport stands, flooding it and its surroundings.</p>

            <p>After Hurricane Fay, which was not a particularly strong hurricane, the airport suffered extensive damage. After Hurricane Fabian, the roof nearly collapsed, which would have completely destroyed the terminal. Next time we may not be so lucky.</p>

            <p>As long as the terminal is in its current location, it will always be susceptible to storm damage because it’s located too close to the water. That’s why the airport redevelopment project would move the terminal 300 meters away from Castle Harbour and raise it 5 meters above sea level to help protect the building from storm damage. Bermuda’s economy and people suffer when our airport has to be shut down, which is going to happen more and more often as long as we continue to neglect this problem.</p>
            <br>
            <h4>Why not just repair the current airport?</h4>
            <br>
            <p>There are some who argue that we should simply fix the current terminal rather than build a new one. Yet repairing the terminal would cost at least $115 million – and Bermuda would still be left with an old airport. The maintenance problems might go away temporarily, but it would still be the old airport with all its faults and inconveniences.<p>

            <p>The repaired facility would not have the features you find in modern airports, like jet bridges, and it would not be wheelchair-friendly. Above all, the airport would still be located too close to the water.</p>
        </div>
    </div>
    <!-- /.row -->

    <hr>



    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-7">
                <!-- <p>Copyright &copy; Your Website 2014</p> -->
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

app/views/contact/contact.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Contact
                <!-- <small>Subheading</small> -->
            </h1>
            <ol class="breadcrumb">
                <li><a href="index.html">Home</a>
                </li>
                <li class="active">Contact</li>
            </ol>
        </div>
    </div>
    <!-- /.row -->

    <!-- Content Row -->
    <div class="row">
        <!-- Map Column -->
        <div class="col-md-8">
            <!-- Embedded Google Map -->
            <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3372.692997195529!2d-64.78485258474278!3d32.2932310158018!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8a2d146dc5eee77d%3A0x4475e4c56b9d2fb0!2s58+Reid+Street%2C+Bermuda!5e0!3m2!1sen!2sus!4v1464618385701"></iframe>
        </div>
        <!-- Contact Details Column -->
        <div class="col-md-4">
            <h3>Contact Details</h3>
            <p>
              58 Reid Street, Hamilton,
              <br>HM11, Bermuda<br>
            </p>
            <p><i class="fa fa-phone"></i>
                <abbr title="Phone">P</abbr>: 441-294-3264</p>
            <p><i class="fa fa-envelope-o"></i>
                <abbr title="Email">E</abbr>: <a href="mailto:name@example.com">info@oba.bm</a>
            </p>

        </div>
    </div>
    <!-- /.row -->

    <!-- Contact Form -->
    <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
    <div class="row">
        <div class="col-md-8">
            <h3>Send us a Message</h3>
            <form name="sentMessage" id="contactForm" novalidate>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Full Name:</label>
                        <input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                        <p class="help-block"></p>
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Phone Number:</label>
                        <input type="tel" class="form-control" id="phone" required data-validation-required-message="Please enter your phone number.">
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Email Address:</label>
                        <input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Message:</label>
                        <textarea rows="10" cols="100" class="form-control" id="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
                    </div>
                </div>
                <div id="success"></div>
                <!-- For success/fail messages -->
                <button type="submit" class="btn btn-primary">Send Message</button>
            </form>
        </div>

    </div>

app/views/home/_article.html.erb
<% @articles.each do |a| %>
  <div class="col-sm-3">
      <div class="panel panel-default text-center news">
        <!-- logo image -->
          <div class="logo">
              <%= image_tag(a.outlet.image, class: "news_image") %>
          </div>
        <!-- headline -->
          <div class="panel-body news headline">
              <h4><a href="<%= a.url %>"><%=a.headline%></a></h4>
          </div>
        <!-- published date -->
            <div class="panel-body news date">
              <p><%= a.date_published.strftime("%B %e %Y") %></p>
            </div>
        <!-- content -->
          <div class="panel-body">
              <p><%= a.content %><p>
          </div>
      </div>
  </div>
  <% end %>

app/views/home/home.html.erb
<!-- Script to Activate the Carousel -->

  <!-- <script>

  $('.carousel').carousel({
      interval: 5000 //changes the speed
  })
  </script> -->
<%= javascript_include_tag 'home', 'data-turbolinks-track' => true %>

<!-- Header Carousel -->
<div id="faqHeader">
  <header id="myCarousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
          <li data-target="#myCarousel" data-slide-to="3"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
          <div class="item active">
              <div class="fill" style="background-image">
                <%= link_to(airport_path) do %>
                  <%= image_tag("airport.jpg", class: "fill") %>
                <% end %>
              </div>
              <div class="carousel-caption">
                  <h2><%= link_to "Why Bermuda Needs a New Airport Terminal", airport_path, class: "homepage" %></h2>
              </div>
          </div>
          <div class="item">
            <div class="fill" style="background-image">
              <%= link_to(deal_path) do %>
                <%= image_tag("sunset.jpg", class: "fill")%>
              <% end %>
            </div>
              <div class="carousel-caption">
                  <h2><%= link_to "The Airport Project is a Great Deal for Bermuda", deal_path, class: "homepage"%> </h2>
              </div>
          </div>

          <div class="item">
            <div class="fill" style="background-image">
              <%= link_to(jobs_path) do %>
                <%= image_tag("new_staff.jpg", class: "fill") %>
              <% end %>
            </div>
              <div class="carousel-caption">
                  <h2><%= link_to "The New Airport Terminal Will Create Jobs & Improve the Economy", deal_path, class: "homepage" %> </h2>
              </div>
          </div>

          <div class="item">
                <div class="fill" style="background-image">
                  <%= link_to("deal.html#schools") do %>
                    <%= image_tag("new_kids.jpg", class: "fill") %>
                    <% end %>
                </div>
                <div class="carousel-caption">
                    <h2><%= link_to("Having Aecon pay for the airport will free up money for after school programs", "deal.html#schools") %></h2>
                </div>
            </div>

      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="icon-prev"></span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="icon-next"></span>
      </a>
  </header>

<!-- Marketing Icons Section -->
  <div class="background">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                A New Airport – Without New Debt
            </h1>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-newspaper-o"></i><a href="news.html"> Airport News</a></h4>
                </div>
                <div class="panel-body">
                    <%= render "article" %>
                  </div>
            </div>
        </div>

        <div class="col-md-4">
            <div id="custom" class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-check"></i><a href="facts.html"> Get the Facts</a></h4>
                </div>
                <div class="panel-body">
                    <p>There’s been a lot of disinformation spread about the airport redevelopment project. It’s time to separate the truth from fiction.</p>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-compass"></i><a href="faq.html">FAQ</a></h4>
                </div>
                <div class="panel-body">
                    <p>Find answers to some of the most common questions about the airport redevelopment project.
                      <br>
                      <br>
                  </p>
                </div>
            </div>
        </div>
      </div>

    <!-- Features Section -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">A Great Deal for Bermuda</h2>
        </div>
        <div class="col-md-6">
            <p>The L.F. Wade International Airport is the world’s gateway to Bermuda. It’s the first impression visitors get of our island, and the last thing they see before they leave.</p>
            <p>Yet the current terminal is falling apart. The airport was originally built in the 1940s – and it shows.</p>
            <p>The facility costs Bermudians millions each year to maintain and is prone to flooding. It’s only a matter of time before Bermuda is hit with a storm strong enough to destroy the airport, which would be devastating to the thousands of Bermudians who depend on tourism to make a living.</p>
            <p>Simply put, Bermuda badly needs a new airport, but with government debt at historic levels already, we can’t afford to pay for it.</p>
            <p>That’s why the government has set up an innovative public-private partnership that will enable us to build a new terminal without increasing the public debt or putting more burden on taxpayers. That’s a great deal for Bermuda.</p>
        </div>

        <div class="col-md-6">
          <div class="videoWrapper">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/xfOI31pVBsg" frameborder="0" allowfullscreen></iframe>
          <!-- <video width:"700", height="450" controls >
            <source src="" type="">
          </video> -->
        </div>
        </div>
    </div>
  </div>  <!-- for background -->

    <!-- /.row -->

    <!-- Call to Action Section -->
    <br>
    <div class="well">
        <div class="row">
            <div class="col-md-8">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
            </div>
            <!-- <div class="col-md-4">
                <a class="btn btn-lg btn-default btn-block" href="contact.html">Subscribe for More</a>
            </div> -->
        </div>
    </div>

    <hr>

app/views/home/index.html.erb
<%= javascript_include_tag 'home', 'data-turbolinks-track' => true %>

<!-- Header Carousel -->
  <header id="myCarousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
          <li data-target="#myCarousel" data-slide-to="3"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
          <div class="item active">
              <div class="fill background" style="background-image">
                <%= link_to(airport_path) do %>
                <div class ='carousel-image'>
                  <%= image_tag("airportrendering.jpg", class: "fill") %>
                <% end %>
                </div>
              </div>
              <div class="carousel-caption">
                  <h2><%= link_to "Why Bermuda Needs a New Airport Terminal", airport_path, class: "homepage" %></h2>
              </div>
          </div>
          <div class="item">
            <div class="fill background" style="background-image">
              <%= link_to(deal_path) do %>
              <div class ='carousel-image'>
                <%= image_tag("sunset2.jpg", class: "fill")%>
              <% end %>
              </div>
            </div>
              <div class="carousel-caption">
                  <h2><%= link_to "The Airport Project is a Great Deal for Bermuda", deal_path, class: "homepage"%> </h2>
              </div>
          </div>

          <div class="item">
            <div class="fill background" style="background-image">
              <%= link_to(jobs_path) do %>
              <div class ='carousel-image'>
                <%= image_tag("new_staff2.jpg", class: "fill") %>
              <% end %>
              </div>
            </div>
              <div class="carousel-caption">
                  <h2><%= link_to "The New Airport Terminal Will Create Jobs", jobs_path, class: "homepage" %> </h2>
              </div>
          </div>

          <div class="item">
                <div class="fill background" style="background-image">
                  <%= link_to("deal.html#schools") do %>
                  <div class ='carousel-image'>
                    <%= image_tag("new_kids2.jpg", class: "fill") %>
                    <% end %>
                  </div>
                </div>
                <div class="carousel-caption">
                    <h2><%= link_to("Freeing Up Money To Help Schools & Seniors", "deal.html#schools") %></h2>
                </div>
            </div>

      </div>


      <!-- Controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="icon-prev"></span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="icon-next"></span>
      </a>
  </header>

  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">
              A New Airport – Without New Debt
          </h1>
      </div>
  </div>

<div class="row">
  <div class="col-sm-4">
      <div class="panel panel-default text-center">
          <div class="panel-heading cta">
              <span class="fa-stack fa-5x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-check fa-stack-1x fa-inverse"></i>
              </span>
          </div>
          <div class="panel-body">
              <h4>Get the Facts</h4>
              <p>There’s been a lot of disinformation spread about the airport redevelopment project. It’s time to separate the truth from fiction.</p></p>
              <a href="facts.html" class="btn btn-primary">Learn More</a>
          </div>
      </div>
  </div>

  <div class="col-sm-4">
      <div class="panel panel-default text-center">
          <div class="panel-heading cta">
              <span class="fa-stack fa-5x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-newspaper-o fa-stack-1x fa-inverse"></i>
              </span>
          </div>
          <div class="panel-body">
              <h4>Airport News</h4>
              <p>Read the latest news & columns regarding the airport development.</p><br>
              <a href="news.html" class="btn btn-primary">Learn More</a>
          </div>
      </div>
  </div>

  <div class="col-sm-4">
      <div class="panel panel-default text-center">
          <div class="panel-heading cta">
              <span class="fa-stack fa-5x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-compass fa-stack-1x fa-inverse"></i>
              </span>
          </div>
          <div class="panel-body">
              <h4>Frequently Asked Questions</h4>
              <p>Find answers to some of the most common questions about the airport redevelopment project.</p><br>
              <a href="faq.html" class="btn btn-primary">Learn More</a>
          </div>
      </div>
  </div>
</div> <!-- CTA Row end -->

<br><br>

    <!-- Features Section -->
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">A Great Deal for Bermuda</h2>
        </div>
        <div class="col-md-6">
            <p>The L.F. Wade International Airport is the world’s gateway to Bermuda. It’s the first impression visitors get of our island, and the last thing they see before they leave.</p>
            <p>Yet the current terminal is falling apart. The airport was originally built in the 1940s – and it shows.</p>
            <p>The facility costs Bermudians millions each year to maintain and is prone to flooding. It’s only a matter of time before Bermuda is hit with a storm strong enough to destroy the airport, which would be devastating to the thousands of Bermudians who depend on visitors, both business and pleasure, to make a living.</p>
            <p>Simply put, Bermuda badly needs a new airport, but with government debt at historic levels already, we can’t afford to pay for it.</p>
            <p>That’s why the government has set up a public-private partnership that will enable us to build a new terminal without increasing the public debt or putting more burden on taxpayers. That’s a great deal for Bermuda.</p>
        </div>

    <div class="col-md-6">
      <div class="videoWrapper">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/twq3iz3jHSM" frameborder="0" allowfullscreen></iframe>
          <!-- <video width:"700", height="450" controls >
            <source src="" type="">
          </video> -->
      </div>
    </div>
</div>

    <br><br><br>
  <!-- News Section -->

  <div class="row">
    <%= render partial: "article" %>
  </div>

    <hr>

app/views/news/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Home', root_path %> |
<%= link_to 'Back', admin_news_path %>

app/views/news/index.html.erb
<br>

<%= link_to 'New Article', admin_news_new_path %>

<br>
<br>

<% @articles.each do |a| %>

  <div class="row">
      <div class="col-md-7">
          <%= image_tag(a.outlet.image, class: "news_image") %>
          <h3><%=a.headline%></h3>
          <h5><%= a.date_published.strftime("%B %e %Y") %></h5>
          <p><%=a.content%></p>
          <%= link_to 'Edit', edit_news_path(a), class: "btn btn-primary" %>
          <%= link_to 'Delete', edit_news_path(a), class: "btn btn-primary" %>
          <!-- <a class="btn btn-primary">Edit Article</i></a>
          <a class="btn btn-primary" href="<%= a.url %>">Delete Article</i></a> -->
      </div>
  </div>

  <hr>

<% end %>

app/views/news/show.html.erb
<div class="row">
    <div class="col-md-7">
        <%= image_tag(@article.outlet.image, class: "news_image") %>
        <h3><%=@article.headline%></h3>
        <h5><%= @article.date_published.strftime("%B %e %Y") %></h5>
        <p><%=@article.content%></p>
        <%= link_to 'Edit', edit_news_path(@article), class: "btn btn-primary" %>
        <%= link_to 'Delete', edit_news_path(@article), class: "btn btn-primary" %>
        <!-- <a class="btn btn-primary">Edit Article</i></a>
        <a class="btn btn-primary" href="<%= a.url %>">Delete Article</i></a> -->
    </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>